version: '3'
services:
  web:
    build:
      context: .
    volumes:
      - ".:/app"
      # Mount these directories to guarantee that they are empty and do not have any OS specific binaries
      # This step is only necessary for docker-compose because they are ignored in the Dockerfile.
      - "/app/deps"
      - "/app/_build"
      - "/app/assets/node_modules"
    ports:
      - 4000:4000
    depends_on:
      - db_dev
      - db_test

  db_dev:
    image: postgres:11-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: phoenix
      POSTGRES_DB: phoenix_dev
      POSTGRES_PASSWORD: phoenix
    volumes:
      - postgres-data:/var/lib/postgresql/data

  db_test:
    image: postgres:11-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: phoenix
      POSTGRES_DB: phoenix_test
      POSTGRES_PASSWORD: phoenix

volumes:
  postgres-data:
