import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
host_url =
  System.fetch_env!("HOST") ||
    raise """
    environment variable HOST is missing.
    For example: www.phoenix.com
    """

secret_key_base =
  System.get_env("SECRET_KEY_BASE") ||
    raise """
    environment variable SECRET_KEY_BASE is missing.
    You can generate one by calling: mix phx.gen.secret
    """

config :<%= app_name %>, <%= web_module %>.Endpoint,
  url: [host: host_url, port: 80],
  http: [
    port: String.to_integer(System.get_env("PORT") || "4000"),
    transport_options: [socket_opts: [:inet6]]
  ],
  cache_static_manifest: "priv/static/cache_manifest.json",
  secret_key_base: secret_key_base,
  server: true

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.

# Read connection string to database. Print error message if not set
database_url =
  System.get_env("DATABASE_URL") ||
    raise """
    environment variable DATABASE_URL is missing.
    For example: postgres://USER:PASS@HOST/DATABASE
    """

# Increase database connection pool size for production or use default
config :<%= app_name %>, <%= app_module %>.Repo,
  pool_size: String.to_integer(System.get_env("POOL_SIZE") || "10"),
  url: database_url

# Do not print debug messages in production
config :logger, level: :info
