FROM elixir:1.11-alpine
WORKDIR /app
ENV MIX_ENV="test"

# We need GIT to resolve mix dependencies
# Bash is nice to enter the container
RUN apk update && apk upgrade && \
  apk add git bash

RUN mix local.hex --force

COPY mix.exs mix.lock ./
RUN mix deps.get --force && \
  mix local.rebar --force && \
  mix deps.compile

COPY . .
