FROM elixir:1.11-alpine
WORKDIR /app

# We need GIT to resolve mix dependencies
# and inotify-tools for code reloads.
# Bash is nice to enter the container
RUN apk update && apk upgrade && \
  apk add inotify-tools git bash

RUN mix local.hex --force && \
  mix archive.install --force hex phx_new 1.5.7

COPY mix.exs mix.lock ./
RUN mix deps.get --force && \
  mix local.rebar --force && \
  mix deps.compile

COPY . .

EXPOSE 4000
CMD mix phx.server
